version: '3.8'

services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "16686:16686"  # Jaeger UI
      - "4318:4318"  # OTLP HTTP (same protocol as HyperDX)
      - "4317:4317"  # OTLP gRPC
    restart: unless-stopped
