name: Build and deploy

on:
  push:
    branches: [master]
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-deploy
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

permissions:
  contents: read

env:
  DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
  ORDERBOOK: "0x881cf4c0764e733d9C387f3858eE87CcA04AFFe0"
  ORDER_OWNER: "0x71b94911FD1CE621FC40970450004c544e5287a8"
  DEPLOYMENT_BLOCK: 34844164
  REGISTRY_NAME: stox

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ env.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Build Docker image
        run: |
          SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-7)
          echo "SHORT_SHA=$SHORT_SHA" >> $GITHUB_ENV

          docker build \
            -t registry.digitalocean.com/${{ env.REGISTRY_NAME }}/schwarbot:$SHORT_SHA \
            -t registry.digitalocean.com/${{ env.REGISTRY_NAME }}/schwarbot:latest .

      - name: Log in to DO Container Registry
        run: doctl registry login --expiry-seconds 1200

      - name: Verify required files exist
        run: |
          echo "Checking for required files..."
          ls -la .env.example docker-compose.template.yaml Dockerfile.grafana grafana-datasource.yaml prep-docker-compose.sh
          echo "File verification complete"

      - name: Encode file contents
        run: |
          echo "ENV_TEMPLATE=$(base64 -w 0 .env.example)" >> $GITHUB_ENV
          echo "DOCKER_COMPOSE_TEMPLATE=$(base64 -w 0 docker-compose.template.yaml)" >> $GITHUB_ENV
          echo "GRAFANA_DOCKERFILE=$(base64 -w 0 Dockerfile.grafana)" >> $GITHUB_ENV
          echo "GRAFANA_DATASOURCE_YAML=$(base64 -w 0 grafana-datasource.yaml)" >> $GITHUB_ENV
          echo "PREP_SCRIPT=$(base64 -w 0 prep-docker-compose.sh)" >> $GITHUB_ENV

      - name: Push image to DO Registry
        run: |
          docker push registry.digitalocean.com/${{ env.REGISTRY_NAME }}/schwarbot:${{ env.SHORT_SHA }}
          docker push registry.digitalocean.com/${{ env.REGISTRY_NAME }}/schwarbot:latest

      - name: Deploy to Droplet
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: root
          key: ${{ secrets.DROPLET_SSH_KEY }}
          envs: DIGITALOCEAN_ACCESS_TOKEN,REGISTRY_NAME,SHORT_SHA,WS_RPC_URL,ORDERBOOK,ORDER_OWNER,DEPLOYMENT_BLOCK,SCHWAB_APP_KEY,SCHWAB_APP_SECRET,ALPACA_API_KEY,ALPACA_API_SECRET,ENCRYPTION_KEY,ENV_TEMPLATE,DOCKER_COMPOSE_TEMPLATE,GRAFANA_DOCKERFILE,GRAFANA_DATASOURCE_YAML,PREP_SCRIPT,GRAFANA_ADMIN_PASSWORD
          script: |
            set -euo pipefail

            # Create log directory and setup logging
            mkdir -p /var/log/schwarbot
            TIMESTAMP=$(date +%Y-%m-%d-%H%M%S)
            DEPLOY_LOG="/var/log/schwarbot/deploy-${TIMESTAMP}.log"
            DOCKER_LOG="/var/log/schwarbot/docker-${TIMESTAMP}.log"

            # Function to log and execute commands
            log_exec() {
              echo "$(date '+%Y-%m-%d %H:%M:%S') - $*" | tee -a "${DEPLOY_LOG}"
              "$@" 2>&1 | tee -a "${DEPLOY_LOG}"
              return ${PIPESTATUS[0]}
            }

            # Function to perform automatic rollback on deployment failure
            perform_rollback() {
              echo "$(date '+%Y-%m-%d %H:%M:%S') - DEPLOYMENT FAILED - Attempting automatic rollback" | tee -a "${DEPLOY_LOG}" >&2

              cd /mnt/volume_nyc3_01

              # Check if required backup files exist
              if [ ! -f "docker-compose.yaml.backup" ] || [ ! -f ".env.backup" ]; then
                echo "$(date '+%Y-%m-%d %H:%M:%S') - No backup files found, cannot rollback (possibly first deployment)" | tee -a "${DEPLOY_LOG}" >&2
                echo "$(date '+%Y-%m-%d %H:%M:%S') - Deployment failed without rollback capability" | tee -a "${DEPLOY_LOG}" >&2
                exit 1
              fi

              echo "$(date '+%Y-%m-%d %H:%M:%S') - Backup files found, performing rollback..." | tee -a "${DEPLOY_LOG}" >&2

              # Stop failed containers
              echo "$(date '+%Y-%m-%d %H:%M:%S') - Stopping failed containers..." | tee -a "${DEPLOY_LOG}"
              docker compose down 2>&1 | tee -a "${DEPLOY_LOG}" || true

              # Restore backed-up configuration
              echo "$(date '+%Y-%m-%d %H:%M:%S') - Restoring backed-up configuration..." | tee -a "${DEPLOY_LOG}"
              cp -p docker-compose.yaml.backup docker-compose.yaml
              cp -p .env.backup .env

              # Conditionally restore grafana config files if backups exist
              if [ -f "grafana-datasource.yaml.backup" ]; then
                echo "$(date '+%Y-%m-%d %H:%M:%S') - Restoring grafana-datasource.yaml from backup" | tee -a "${DEPLOY_LOG}"
                cp -p grafana-datasource.yaml.backup grafana-datasource.yaml
              else
                echo "$(date '+%Y-%m-%d %H:%M:%S') - No backup found for grafana-datasource.yaml, skipping" | tee -a "${DEPLOY_LOG}"
              fi

              if [ -f "Dockerfile.grafana.backup" ]; then
                echo "$(date '+%Y-%m-%d %H:%M:%S') - Restoring Dockerfile.grafana from backup" | tee -a "${DEPLOY_LOG}"
                cp -p Dockerfile.grafana.backup Dockerfile.grafana
              else
                echo "$(date '+%Y-%m-%d %H:%M:%S') - No backup found for Dockerfile.grafana, skipping" | tee -a "${DEPLOY_LOG}"
              fi

              # Restart with old configuration
              echo "$(date '+%Y-%m-%d %H:%M:%S') - Starting containers with restored configuration..." | tee -a "${DEPLOY_LOG}"
              docker compose up -d 2>&1 | tee -a "${DEPLOY_LOG}"

              sleep 10

              # Verify rollback succeeded
              echo "$(date '+%Y-%m-%d %H:%M:%S') - Verifying rollback..." | tee -a "${DEPLOY_LOG}"
              docker compose ps 2>&1 | tee -a "${DEPLOY_LOG}"

              echo "$(date '+%Y-%m-%d %H:%M:%S') - Rollback completed - production restored to previous version" | tee -a "${DEPLOY_LOG}" >&2
              echo "$(date '+%Y-%m-%d %H:%M:%S') - Deployment failed but system is stable on previous version" | tee -a "${DEPLOY_LOG}" >&2
              exit 1
            }

            # Function to validate required environment variables
            validate_required_env() {
              local missing_vars=()

              for var in REGISTRY_NAME SHORT_SHA DATA_VOLUME_PATH GRAFANA_ADMIN_PASSWORD \
                         WS_RPC_URL SCHWAB_APP_KEY SCHWAB_APP_SECRET ALPACA_API_KEY \
                         ALPACA_API_SECRET ENCRYPTION_KEY; do
                local value="${!var:-}"
                if [ -z "$value" ]; then
                  missing_vars+=("$var")
                fi
              done

              if [ ${#missing_vars[@]} -gt 0 ]; then
                echo "$(date '+%Y-%m-%d %H:%M:%S') - ERROR: Required environment variables are missing:" | tee -a "${DEPLOY_LOG}" >&2
                for var in "${missing_vars[@]}"; do
                  echo "  - $var" | tee -a "${DEPLOY_LOG}" >&2
                done
                echo "$(date '+%Y-%m-%d %H:%M:%S') - Deployment aborted due to missing configuration" | tee -a "${DEPLOY_LOG}" >&2
                exit 1
              fi
            }

            # Start deployment logging
            echo "$(date '+%Y-%m-%d %H:%M:%S') - Starting deployment of schwarbot:${SHORT_SHA}" | tee "${DEPLOY_LOG}"
            echo "Deployment logs: ${DEPLOY_LOG}" | tee -a "${DEPLOY_LOG}"
            echo "Container logs will be saved to: ${DOCKER_LOG}" | tee -a "${DEPLOY_LOG}"

            # Set production data volume path
            export DATA_VOLUME_PATH="/mnt/volume_nyc3_01"

            # Validate all required environment variables
            echo "$(date '+%Y-%m-%d %H:%M:%S') - Validating required environment variables..." | tee -a "${DEPLOY_LOG}"
            validate_required_env
            echo "$(date '+%Y-%m-%d %H:%M:%S') - All required environment variables present" | tee -a "${DEPLOY_LOG}"

            # Docker login
            echo "$(date '+%Y-%m-%d %H:%M:%S') - Logging into Docker registry" | tee -a "${DEPLOY_LOG}"
            echo "${DIGITALOCEAN_ACCESS_TOKEN}" | \
              docker login registry.digitalocean.com -u unused --password-stdin 2>&1 | tee -a "${DEPLOY_LOG}"

            # Decode and create files from base64-encoded content
            echo "$(date '+%Y-%m-%d %H:%M:%S') - Creating configuration files from templates" | tee -a "${DEPLOY_LOG}"

            # Create required files in deployment directory
            echo "$DOCKER_COMPOSE_TEMPLATE" | base64 -d > /mnt/volume_nyc3_01/docker-compose.template.yaml
            echo "$GRAFANA_DOCKERFILE" | base64 -d > /mnt/volume_nyc3_01/Dockerfile.grafana
            echo "$GRAFANA_DATASOURCE_YAML" | base64 -d > /mnt/volume_nyc3_01/grafana-datasource.yaml
            echo "$PREP_SCRIPT" | base64 -d > /mnt/volume_nyc3_01/prep-docker-compose.sh
            chmod +x /mnt/volume_nyc3_01/prep-docker-compose.sh

            # Backup current working configuration for rollback capability
            cd /mnt/volume_nyc3_01
            if [ -f "docker-compose.yaml" ] && [ -f ".env" ]; then
              echo "$(date '+%Y-%m-%d %H:%M:%S') - Backing up current configuration for rollback" | tee -a "${DEPLOY_LOG}"
              cp -p docker-compose.yaml docker-compose.yaml.backup
              cp -p .env .env.backup

              # Also backup grafana config files if they exist
              [ -f "grafana-datasource.yaml" ] && cp -p grafana-datasource.yaml grafana-datasource.yaml.backup
              [ -f "Dockerfile.grafana" ] && cp -p Dockerfile.grafana Dockerfile.grafana.backup
            else
              echo "$(date '+%Y-%m-%d %H:%M:%S') - No existing configuration to backup (first deployment)" | tee -a "${DEPLOY_LOG}"
            fi

            # Generate docker-compose.yaml using prep script
            log_exec ./prep-docker-compose.sh --prod

            # Pull images and stop existing services
            log_exec docker compose pull
            log_exec docker compose down || true

            # Ensure database directory exists and has proper permissions
            log_exec chmod 755 /mnt/volume_nyc3_01

            # Create .env file for container configuration using .env.example as template
            echo "$(date '+%Y-%m-%d %H:%M:%S') - Creating .env file from template" | tee -a "${DEPLOY_LOG}"

            # Set deployment-specific values for .env file
            export DATABASE_URL="sqlite:///data/schwab.db"
            export RUST_LOG="rain_schwab=debug"

            # Create .env file using template with envsubst
            echo "$ENV_TEMPLATE" | base64 -d | envsubst > /mnt/volume_nyc3_01/.env
            chmod 600 /mnt/volume_nyc3_01/.env

            # Start services with docker-compose
            # Export sensitive variables so docker-compose can read them from environment
            export ENCRYPTION_KEY="${ENCRYPTION_KEY}"
            export GRAFANA_ADMIN_PASSWORD="${GRAFANA_ADMIN_PASSWORD}"

            echo "$(date '+%Y-%m-%d %H:%M:%S') - Starting services with docker-compose" | tee -a "${DEPLOY_LOG}"
            if ! docker compose up -d 2>&1 | tee -a "${DEPLOY_LOG}"; then
              echo "$(date '+%Y-%m-%d %H:%M:%S') - Failed to start containers" | tee -a "${DEPLOY_LOG}" >&2
              perform_rollback
            fi

            # Unset sensitive variables after use
            unset ENCRYPTION_KEY
            unset GRAFANA_ADMIN_PASSWORD

            # Wait for containers to fully start
            echo "$(date '+%Y-%m-%d %H:%M:%S') - Waiting for containers to start..." | tee -a "${DEPLOY_LOG}"
            sleep 15

            # Check if services are running - use docker ps as primary check
            echo "$(date '+%Y-%m-%d %H:%M:%S') - Checking container status..." | tee -a "${DEPLOY_LOG}"

            # Debug: show what containers are actually running
            docker ps --format "table {{.Names}}\t{{.Status}}" | tee -a "${DEPLOY_LOG}"

            if ! docker ps --format "{{.Names}}" | grep -q "^schwarbot$"; then
              echo "$(date '+%Y-%m-%d %H:%M:%S') - Schwarbot container not found in docker ps" | tee -a "${DEPLOY_LOG}" >&2
              docker compose logs schwarbot 2>&1 | tee "${DOCKER_LOG}" | tee -a "${DEPLOY_LOG}"
              echo "Full container logs saved to: ${DOCKER_LOG}" | tee -a "${DEPLOY_LOG}" >&2
              perform_rollback
            fi

            if ! docker ps --format "{{.Names}}" | grep -q "^alpacabot$"; then
              echo "$(date '+%Y-%m-%d %H:%M:%S') - Alpacabot container not found in docker ps" | tee -a "${DEPLOY_LOG}" >&2
              docker compose logs alpacabot 2>&1 | tee -a "${DEPLOY_LOG}"
              perform_rollback
            fi

            if ! docker ps --format "{{.Names}}" | grep -q "^grafana$"; then
              echo "$(date '+%Y-%m-%d %H:%M:%S') - Grafana container not found in docker ps" | tee -a "${DEPLOY_LOG}" >&2
              docker compose logs grafana 2>&1 | tee -a "${DEPLOY_LOG}"
              perform_rollback
            fi

            echo "$(date '+%Y-%m-%d %H:%M:%S') - All containers confirmed running" | tee -a "${DEPLOY_LOG}"

            # Capture initial container logs
            echo "$(date '+%Y-%m-%d %H:%M:%S') - Services started successfully, capturing logs..." | tee -a "${DEPLOY_LOG}"
            docker compose logs schwarbot 2>&1 | tee "${DOCKER_LOG}"
            docker compose logs alpacabot 2>&1 | tee -a "${DOCKER_LOG}"

            # Check for errors in schwarbot logs
            if docker compose logs schwarbot 2>&1 | grep -q "error\|panic\|failed"; then
              echo "$(date '+%Y-%m-%d %H:%M:%S') - Schwarbot errors detected in logs" | tee -a "${DEPLOY_LOG}" >&2
              docker compose logs --tail 20 schwarbot 2>&1 | tee -a "${DEPLOY_LOG}"
              echo "Full container logs saved to: ${DOCKER_LOG}" | tee -a "${DEPLOY_LOG}" >&2
              perform_rollback
            fi

            # Check for errors in alpacabot logs
            if docker compose logs alpacabot 2>&1 | grep -q "error\|panic\|failed"; then
              echo "$(date '+%Y-%m-%d %H:%M:%S') - Alpacabot errors detected in logs" | tee -a "${DEPLOY_LOG}" >&2
              docker compose logs --tail 20 alpacabot 2>&1 | tee -a "${DEPLOY_LOG}"
              echo "Full container logs saved to: ${DOCKER_LOG}" | tee -a "${DEPLOY_LOG}" >&2
              perform_rollback
            fi

            # Cleanup old images
            echo "$(date '+%Y-%m-%d %H:%M:%S') - Cleaning up old images..." | tee -a "${DEPLOY_LOG}"
            log_exec docker image prune -f
            docker images "registry.digitalocean.com/${REGISTRY_NAME}/schwarbot" \
              --format "table {{.Repository}}\t{{.Tag}}\t{{.CreatedAt}}" | \
              tail -n +2 | head -n -3 | awk '{print $1":"$2}' | \
              xargs -r docker rmi 2>&1 | tee -a "${DEPLOY_LOG}" || true

            # Cleanup old logs (keep last 10 deployments)
            echo "$(date '+%Y-%m-%d %H:%M:%S') - Cleaning up old deployment logs..." | tee -a "${DEPLOY_LOG}"
            cd /var/log/schwarbot
            ls -t deploy-*.log 2>/dev/null | tail -n +11 | xargs -r rm -f || true
            ls -t docker-*.log 2>/dev/null | tail -n +11 | xargs -r rm -f || true

            echo "$(date '+%Y-%m-%d %H:%M:%S') - Deployment completed successfully!" | tee -a "${DEPLOY_LOG}"
            echo "Deployment logs: ${DEPLOY_LOG}"
            echo "Container logs: ${DOCKER_LOG}"
        env:
          WS_RPC_URL: ${{ secrets.WS_RPC_URL }}
          SCHWAB_APP_KEY: ${{ secrets.APP_KEY }}
          SCHWAB_APP_SECRET: ${{ secrets.APP_SECRET }}
          ALPACA_API_KEY: ${{ secrets.ALPACA_KEY }}
          ALPACA_API_SECRET: ${{ secrets.ALPACA_SECRET }}
          ENCRYPTION_KEY: ${{ secrets.TOKEN_ENCRYPTION_KEY }}
          GRAFANA_ADMIN_PASSWORD: ${{ secrets.GRAFANA_ADMIN_PASSWORD }}
          ENV_TEMPLATE: ${{ env.ENV_TEMPLATE }}
          DOCKER_COMPOSE_TEMPLATE: ${{ env.DOCKER_COMPOSE_TEMPLATE }}
          GRAFANA_DOCKERFILE: ${{ env.GRAFANA_DOCKERFILE }}
          GRAFANA_DATASOURCE_YAML: ${{ env.GRAFANA_DATASOURCE_YAML }}
          PREP_SCRIPT: ${{ env.PREP_SCRIPT }}
