name: Test Coverage
on: [push]

concurrency:
  group: ${{ github.ref }}-test-coverage
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

jobs:
  rainix:
    runs-on: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - uses: nixbuild/nix-quick-install-action@v30
        with:
          nix_conf: |
            keep-env-derivations = true
            keep-outputs = true
      - name: Restore and save Nix store
        uses: nix-community/cache-nix-action@v6
        with:
          # restore and save a cache using this key
          primary-key: nix-${{ runner.os }}-${{ hashFiles('**/*.nix', '**/flake.lock') }}
          # if there's no cache hit, restore a cache by this prefix
          restore-prefixes-first-match: nix-${{ runner.os }}-
          # collect garbage until the Nix store size (in bytes) is at most this number
          gc-max-store-size-linux: 10G

      - run: nix run .#prepSolArtifacts
      - run: cp -v .env.example .env
      - run: nix develop -c sqlx db create
      - run: nix develop -c sqlx migrate run
      - run: nix run .#checkTestCoverage
      - run: git diff --exit-code
